using System.Windows;
using PrimerCas4.Table;

namespace PrimerCas4
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void AutoColumns_Click(object sender, RoutedEventArgs e)
        {
            var s = new TableExampleAutoGenerated();
            s.Show();
        }

        private void ManualColumns_Click(object sender, RoutedEventArgs e)
        {
            var s = new TableExampleManuallyGenerated();
            s.Show();
        }

        private void Binding_Click(object sender, RoutedEventArgs e)
        {
            var s = new TableExampleBinding();
            s.Show();
        }
    }
}
